### ISSUE TITLE
能再加入一个进度条框么？

### ISSUE THREAD

**Issue by hegelsu** [sunwangxia/CocoaDialog#1]

**Comment by SunBerwin** [comment]
这个可以有，不知道你那边需求是怎样的，需要有精确进度的进度条还是转圈圈，或者我考虑一下两个一起做上去吧。今天有点晚了，明后天我看看加上去放个更新出来吧，API设计成跟添加输入框类似你觉得怎么样

**Comment by SunBerwin** [comment]
这个可以有，不知道你那边需求是怎样的，需要有精确进度的进度条还是转圈圈，或者我考虑一下两个一起做上去吧。今天有点晚了，明后天我看看加上去放个更新出来吧，API设计成跟添加输入框类似你觉得怎么样

**Comment by hegelsu** [comment]
![1](https://user-images.githubusercontent.com/6879123/35331676-2be42ec0-0143-11e8-9f25-64af67165da0.png)
差不多这样吧

**Comment by SunBerwin** [comment]
这样的话直接使用ProgressDialog就可以了。目前1.2.0版增加了ProgressBar的支持，不过跟这有点不太一样，还是有具体进度的进度条显示效果会比较好看，例如文件下载提示框，具体使用方法可在最新的demo中见到

**Comment by hegelsu** [comment]
好的
